language: python
python:
  - "3.6"
install:
  - pip3 install -r requirements.txt
  - make build install
script:
  - todx
  - todx add Make me a sandwich +awesome +crazy
  - todx
  - todx -v
  - todx +awesome
  - pytest
  - pip uninstall todx
  - pip install todx
  - todx